### ISSUE TITLE
Raw heal-weighted mastery is not quite the ideal metric

### ISSUE THREAD

**Issue by talchas** [rubensayshi/wcl-rdruid-mastery#13]
For the typical spreadsheet use we actually want the weighted average of effective healing _as if we had no mastery_ (from gear or the baseline mastery). This can be reasonably easily approximated with the mastery value logged at the beginning of the encounter, or can be more accurately computed by also tracking mastery procs from 2pc/map/etc.

**Comment by rubensayshi** [comment]
https://github.com/rubensayshi/wcl-rdruid-mastery/commit/b6885798c168beb6b4d0fb70df9b0aeb844b5449
